## Build final updatecli docker image
#  We on purpose release artifacts created by goreleaser
#  located in the dist directory

## The binary is statically linked (CGO_ENABLED=0 in .goreleaser.yml), so the image only
#  needs CA certificates, which distroless provides, and no shell or package manager.
#  The base is not pinned to the build platform: nothing runs at build time anymore, and
#  pinning it gave the arm64 image an amd64 base.
FROM gcr.io/distroless/static-debian13:latest@sha256:58133991db06659feaabe0f4e97a35cebf15ef4ea08f8a4c6d2ee5f75e4aa6a0

LABEL maintainer="Olivier Vernin <me@olblak.com>"

# Dynamic labels are defined from the goreleaser configuration ".goreleaser.yaml"
LABEL org.opencontainers.image.authors="Olivier Vernin<me@olblak.com>"
LABEL org.opencontainers.image.url="https://github.com/updatecli/udash"
LABEL org.opencontainers.image.documentation="https://www.updatecli.io/docs/prologue/introduction/"
LABEL org.opencontainers.image.title="Udash"
LABEL org.opencontainers.image.description="A declarative update manager UI"
LABEL org.opencontainers.image.base.name="ghcr.io/updatecli/udash"
LABEL org.opencontainers.image.licenses="AGPL-3.0"
LABEL org.opencontainers.image.source = "https://github.com/updatecli/udash" 

# Available files only matched against the binaries generated by the builds section
# and packages generated by the nfpms section.
COPY udash  /usr/local/bin/udash

# Same uid and home as the previous Debian based image, so existing volume mounts such as
# /home/udash/.udash/config.yaml keep working.
ENV HOME=/home/udash
WORKDIR /home/udash
USER 1000:1000

ENTRYPOINT [ "/usr/local/bin/udash" ]
