## Build final updatecli docker image
#  We on purpose release artifacts created by goreleaser
#  located in the dist directory

## Goreleaser requires the "--platform" to handle multi-platform builds
# hadolint ignore=DL3029
FROM --platform=${BUILDPLATFORM} debian:stable-slim

LABEL maintainer="Olivier Vernin <me@olblak.com>"

# Dynamic labels are defined from the goreleaser configuration ".goreleaser.yaml"
LABEL org.opencontainers.image.authors="Olivier Vernin<me@olblak.com>"
LABEL org.opencontainers.image.url="https://github.com/updatecli/udash"
LABEL org.opencontainers.image.documentation="https://www.updatecli.io/docs/prologue/introduction/"
LABEL org.opencontainers.image.title="Udash"
LABEL org.opencontainers.image.description="A declarative update manager UI"
LABEL org.opencontainers.image.base.name="ghcr.io/updatecli/udash"
LABEL org.opencontainers.image.licenses="AGPL-3.0"
LABEL org.opencontainers.image.source = "https://github.com/updatecli/udash" 

## The latest version of these "generic" package is always required
# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
        ca-certificates \
        curl \
        tar \
        unzip \
        wget &&\ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Available files only matched against the binaries generated by the builds section
# and packages generated by the nfpms section.
COPY udash  /usr/local/bin/udash

RUN \
  useradd -d /home/udash -U -u 1000 -m udash && \
  mkdir /etc/udash && \
  chmod 0660 /etc/udash && \
  chown root:udash /etc/udash

USER udash

WORKDIR /home/udash

RUN mkdir /home/udash/.udash

ENTRYPOINT [ "/usr/local/bin/udash" ]

