// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/": {
            "get": {
                "description": "Landing page of the API",
                "tags": [
                    "Landing"
                ],
                "summary": "Landing page",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/ping": {
            "get": {
                "description": "Ping the API to check if it's running",
                "tags": [
                    "Ping"
                ],
                "summary": "Ping the API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/api/pipeline/config/conditions": {
            "get": {
                "description": "List all configuration conditions from the database",
                "tags": [
                    "Configuration Conditions"
                ],
                "summary": "List all configuration conditions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the configuration condition",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Kind of the configuration condition",
                        "name": "kind",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Configuration of the condition",
                        "name": "config",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Limit the number of reports returned, default is 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page number for pagination, default is 1",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ConditionConfigResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a configuration condition from the database",
                "tags": [
                    "Configuration Conditions"
                ],
                "summary": "Delete a configuration condition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the configuration condition to delete",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/api/pipeline/config/conditions/search": {
            "post": {
                "description": "Search for configuration conditions in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuration Conditions"
                ],
                "summary": "Search configuration conditions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ConditionConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/api/pipeline/config/kinds": {
            "post": {
                "description": "Search for configuration by kind in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuration"
                ],
                "summary": "Search configuration by kind",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ConfigKindResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/api/pipeline/config/sources": {
            "get": {
                "description": "List all configuration sources from the database",
                "tags": [
                    "Configuration Sources"
                ],
                "summary": "List all configuration sources",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the configuration source",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Kind of the configuration source",
                        "name": "kind",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Configuration of the source",
                        "name": "config",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Limit the number of reports returned, default is 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page number for pagination, default is 1",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.SourceConfigResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a configuration source from the database",
                "tags": [
                    "Configuration Sources"
                ],
                "summary": "Delete a configuration source",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the configuration source to delete",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/api/pipeline/config/sources/search": {
            "post": {
                "description": "Search for configuration sources in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuration Sources"
                ],
                "summary": "Search configuration sources",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.SourceConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/api/pipeline/config/targets": {
            "get": {
                "description": "List all configuration targets from the database",
                "tags": [
                    "Configuration Targets"
                ],
                "summary": "List all target configurations.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the configuration target",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Kind of the configuration target",
                        "name": "kind",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Configuration of the target",
                        "name": "config",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Limit the number of reports returned, default is 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page number for pagination, default is 1",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.TargetConfigResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a configuration target from the database",
                "tags": [
                    "Configuration Targets"
                ],
                "summary": "Delete a configuration target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the configuration target to delete",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/api/pipeline/config/targets/search": {
            "post": {
                "description": "Search for configuration targets in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuration Targets"
                ],
                "summary": "Search configuration targets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.TargetConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/api/pipeline/labels": {
            "get": {
                "description": "List labels data from the database with optional filtering",
                "tags": [
                    "Labels"
                ],
                "summary": "List labels",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by label ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by label key",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by label value",
                        "name": "value",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Return only unique label keys (true/false)",
                        "name": "keyonly",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Limit the number of labels returned, default is 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page number for pagination, default is 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time for filtering labels (RFC3339 format)",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time for filtering labels (RFC3339 format)",
                        "name": "end_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ListLabelsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/api/pipeline/labels/search": {
            "post": {
                "description": "Search labels in the database using advanced filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Labels"
                ],
                "summary": "Search labels",
                "parameters": [
                    {
                        "description": "Search parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.SearchLabelsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ListLabelsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/api/pipeline/reports": {
            "get": {
                "description": "List all pipeline reports from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline Reports"
                ],
                "summary": "List all pipeline reports",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SCM ID",
                        "name": "scmid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Limit the number of reports returned, default is 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page number for pagination, default is 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time for filtering reports (RFC3339 format)",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time for filtering reports (RFC3339 format)",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Only return the latest report per pipeline ID, default is true",
                        "name": "latest",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.GetPipelineReportsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new pipeline report in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline Reports"
                ],
                "summary": "Create a new pipeline report",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server.CreatePipelineReportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/api/pipeline/reports/search": {
            "post": {
                "description": "Search pipeline reports in the database using advanced filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline Reports"
                ],
                "summary": "Search pipeline reports",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Limit the number of reports returned, default is 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page number for pagination, default is 1",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.GetPipelineReportsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/api/pipeline/reports/summary": {
            "post": {
                "description": "Return the number of pipeline reports per result for each time bucket of the requested time range.\nBuckets are UTC hours, UTC calendar days, ISO weeks or calendar months depending on the\ngranularity, and the date of an entry is the start of its bucket, formatted as RFC3339.\nEvery report is counted, including several reports of the same pipeline, and buckets without\nany report are returned with a zeroed entry.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline Reports"
                ],
                "summary": "Summarize pipeline reports",
                "parameters": [
                    {
                        "description": "Summary filters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.SearchPipelineReportsSummaryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.SearchPipelineReportsSummaryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/api/pipeline/reports/{id}": {
            "get": {
                "description": "Get the latest pipeline report for a specific ID",
                "tags": [
                    "Pipeline Reports"
                ],
                "summary": "Get a pipeline report by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Report ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.GetPipelineReportByIDResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a pipeline report in the database. Please note that this endpoint is not supported yet.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pipeline Reports"
                ],
                "summary": "Update a pipeline report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Report ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a pipeline report from the database",
                "tags": [
                    "Pipeline Reports"
                ],
                "summary": "Delete a pipeline report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Report ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/api/pipeline/scms": {
            "get": {
                "description": "List SCMs data from the database",
                "tags": [
                    "SCMs"
                ],
                "summary": "List SCMs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the SCM",
                        "name": "scmid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "URL of the SCM",
                        "name": "url",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Branch of the SCM",
                        "name": "branch",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Return a summary of the SCMs",
                        "name": "summary",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Limit the number of reports returned, default is 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page number for pagination, default is 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time for filtering SCMs (RFC3339 format)",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time for filtering SCMs (RFC3339 format)",
                        "name": "end_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ListSCMsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/api/pipeline/scms/search": {
            "post": {
                "description": "Search SCM data using JSON filters. When summary is true, the response contains SCM summary data for all matching SCMs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SCMs"
                ],
                "summary": "Search SCMs",
                "parameters": [
                    {
                        "description": "SCM search filters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.SearchSCMsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ListSCMsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.DefaultResponseModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "condition.Config": {
            "type": "object",
            "properties": {
                "dependsOn": {
                    "description": "\"dependson\" allows to specify the order of execution of resources.\nIt accepts a list of rules like \"(resourceType#)resourceId(:booleanOperator)\".\n\nThe resourceType is optional and can be one of \"condition\", \"source\" or \"target\"\nBy default the resourceType is the current resource type\n\nThe resourceId is the name of the resource to depend on\n\nThe booleanOperator is optional and can be \"AND\" or \"OR\"\n\nexamples:\n   dependson:\n     * condition#myCondition:and\n     * source#mySource\n\nremarks:\n * The parameters \"sourceid\" and \"conditionsids\" affect the order of resource execution.\n * To avoid circular dependencies, the depended resource may need to remove any conditionids or set \"disablesourceinput to true\".",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "deprecatedDependsOn": {
                    "description": "!deprecated, please use dependson\nDeprecatedDependsOn is kept for backward compatibility",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "deprecatedSCMID": {
                    "description": "!deprecated, please use scmid\nDeprecatedSCMID is kept for backward compatibility",
                    "type": "string"
                },
                "deprecatedSourceID": {
                    "description": "! Deprecated in favor of sourceID",
                    "type": "string"
                },
                "disableSourceInput": {
                    "description": "disablesourceinput disable the mechanism to retrieve a default value from a source.",
                    "type": "boolean"
                },
                "failWhen": {
                    "description": "FailWhen allows to reverse a condition expected result from true to false.",
                    "type": "boolean"
                },
                "kind": {
                    "description": "kind specifies the resource kind which defines accepted spec value",
                    "type": "string"
                },
                "name": {
                    "description": "name specifies the resource name",
                    "type": "string"
                },
                "scmid": {
                    "description": "scmid specifies the scm configuration key associated to the current resource",
                    "type": "string"
                },
                "sourceID": {
                    "description": "sourceid specifies which \"source\", based on its ID, is used to retrieve the default value.",
                    "type": "string"
                },
                "spec": {
                    "description": "spec specifies parameters for a specific resource kind"
                },
                "transformers": {
                    "description": "transformers defines how the default input value need to be transformed",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/transformer.Transformer"
                    }
                }
            }
        },
        "database.ReportResultSummaryEntry": {
            "type": "object",
            "properties": {
                "date": {
                    "description": "Date is the start of the bucket, in UTC, formatted as RFC3339.",
                    "type": "string"
                },
                "open_actions": {
                    "description": "OpenActions contains, for each Updatecli result, how many of the reports counted in\nResults also carry an open action, such as a pull request still waiting to be merged.\nIt is a breakdown of Results, not an addition to it, so its counts are always lower\nthan or equal to the matching ones in Results.\n\nThe interesting one is the count reported under the success result: those pipelines\nran fine and had nothing to change only because the change is already waiting in a\npull request.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "results": {
                    "description": "Results contains the number of reports per Updatecli result for that bucket.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "total": {
                    "description": "Total is the number of reports for that bucket, all results combined.",
                    "type": "integer"
                }
            }
        },
        "database.SearchLatestReportData": {
            "type": "object",
            "properties": {
                "conditionConfigIDs": {
                    "description": "ConditionConfigIDs contains the config condition IDs associated with the report.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/pgtype.Hstore"
                        }
                    ]
                },
                "createdAt": {
                    "description": "CreatedAt represents the creation date of the report.",
                    "type": "string"
                },
                "filteredResourceID": {
                    "description": "FilteredResourceID contains the resource config ID that was filtered\nIt allows to identify in the report which resource was used to filter the report.",
                    "type": "string"
                },
                "id": {
                    "description": "ID represents the unique identifier of the report.",
                    "type": "string"
                },
                "name": {
                    "description": "Name represents the name of the report.",
                    "type": "string"
                },
                "report": {
                    "description": "Report contains the report data.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/reports.Report"
                        }
                    ]
                },
                "result": {
                    "description": "Result represents the result of the report.",
                    "type": "string"
                },
                "sourceConfigIDs": {
                    "description": "SourceConfigIDs contains the config source IDs associated with the report.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/pgtype.Hstore"
                        }
                    ]
                },
                "targetConfigIDs": {
                    "description": "TargetConfigIDs contains the config target IDs associated with the report.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/pgtype.Hstore"
                        }
                    ]
                },
                "updatedAt": {
                    "description": "UpdatedAt represents the last update date of the report.",
                    "type": "string"
                }
            }
        },
        "model.ConfigCondition": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/condition.Config"
                },
                "created_at": {
                    "description": "Created_at represent the creation date of the record.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier of the record in the database.",
                    "type": "string"
                },
                "kind": {
                    "description": "Kind represent the kind of the resource configuration.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "Updated_at represent the last update date of the record.",
                    "type": "string"
                }
            }
        },
        "model.ConfigSource": {
            "type": "object",
            "properties": {
                "config": {
                    "description": "Config is the configuration of the source resource.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/source.Config"
                        }
                    ]
                },
                "created_at": {
                    "description": "Created_at represent the creation date of the record.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier of the record in the database.",
                    "type": "string"
                },
                "kind": {
                    "description": "Kind represent the kind of the resource configuration.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "Updated_at represent the last update date of the record.",
                    "type": "string"
                }
            }
        },
        "model.ConfigTarget": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/target.Config"
                },
                "created_at": {
                    "description": "Created_at represent the creation date of the record.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier of the record in the database.",
                    "type": "string"
                },
                "kind": {
                    "description": "Kind represent the kind of the resource configuration.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "Updated_at represent the last update date of the record.",
                    "type": "string"
                }
            }
        },
        "model.Label": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt is the time the label was created",
                    "type": "string"
                },
                "id": {
                    "description": "ID is a unique identifier for the label, generated as a UUID.",
                    "type": "string"
                },
                "key": {
                    "description": "Key is the label name",
                    "type": "string"
                },
                "last_pipeline_report_at": {
                    "description": "LastPipelineReportAt is the time the label was last used in a pipeline report",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt is the time the label was last updated",
                    "type": "string"
                },
                "value": {
                    "description": "Value is the value associated with the label",
                    "type": "string"
                }
            }
        },
        "model.PipelineReport": {
            "type": "object",
            "properties": {
                "conditionConfigIDs": {
                    "description": "ConditionConfigIDs is a list of unique identifiers of the condition configuration associated with the database.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/pgtype.Hstore"
                        }
                    ]
                },
                "created_at": {
                    "description": "Create_at represent the creation date of the record.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier of the record in the database.",
                    "type": "string"
                },
                "labelIDs": {
                    "description": "LabelIDs is a list of unique identifiers of the labels associated with the database.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pipeline": {
                    "description": "Pipeline represent the Updatecli pipeline report.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/reports.Report"
                        }
                    ]
                },
                "pipelineID": {
                    "description": "PipelineID represent the unique identifier of the pipeline.\nSeveral reports can be associated to the same PipelineID.",
                    "type": "string"
                },
                "reportID": {
                    "description": "ReportID represent the ID of the pipeline executed by Updatecli.\ndifferent execution of the same pipeline will have the same ReportID.\nThis value is coming from the pipeline report to improve the search of reports.",
                    "type": "string"
                },
                "result": {
                    "description": "Result represent the result of the pipeline execution.",
                    "type": "string"
                },
                "sourceConfigIDs": {
                    "description": "SourceConfigIDs is a list of unique identifiers of the source configuration associated with the database.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/pgtype.Hstore"
                        }
                    ]
                },
                "targetConfigIDs": {
                    "description": "TargetConfigIDs is a list of unique identifiers of the target configuration associated with the database.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/pgtype.Hstore"
                        }
                    ]
                },
                "targetScmIDs": {
                    "description": "TargetScmIDs is a list of unique identifiers of the scm configuration associated with the database.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "description": "Updated_at represent the last update date of the record.",
                    "type": "string"
                }
            }
        },
        "model.SCM": {
            "type": "object",
            "properties": {
                "branch": {
                    "description": "Branch is the Git branch",
                    "type": "string"
                },
                "created_at": {
                    "description": "Created_at is the time the SCM configuration was created",
                    "type": "string"
                },
                "id": {
                    "description": "ID is a unique identifier for the SCM configuration",
                    "type": "string"
                },
                "updated_at": {
                    "description": "Updated_at is the time the SCM configuration was last updated",
                    "type": "string"
                },
                "url": {
                    "description": "URL is the Git repository URL",
                    "type": "string"
                }
            }
        },
        "pgtype.Hstore": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "reports.Action": {
            "type": "object",
            "properties": {
                "actionUrl": {
                    "description": "Link is the URL of the action",
                    "type": "string"
                },
                "description": {
                    "description": "Description is the description of the action",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier of the action",
                    "type": "string"
                },
                "pipelineTitle": {
                    "description": "PipelineTitle is the title of the pipeline",
                    "type": "string"
                },
                "pipelineURL": {
                    "description": "using a pointer to avoid empty tag",
                    "allOf": [
                        {
                            "$ref": "#/definitions/reports.PipelineURL"
                        }
                    ]
                },
                "targets": {
                    "description": "Targets is the list of targets IDs associated with the action",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/reports.ActionTarget"
                    }
                },
                "title": {
                    "description": "Title is the title of the action",
                    "type": "string"
                }
            }
        },
        "reports.ActionTarget": {
            "type": "object",
            "properties": {
                "changelogs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/reports.ActionTargetChangelog"
                    }
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "reports.ActionTargetChangelog": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "Description is the description of the changelog",
                    "type": "string"
                },
                "title": {
                    "description": "Title is the title of the changelog",
                    "type": "string"
                }
            }
        },
        "reports.CIData": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "reports.PipelineURL": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name is the name of the pipeline",
                    "type": "string"
                },
                "url": {
                    "description": "URL is the URL of the pipeline",
                    "type": "string"
                }
            }
        },
        "reports.Report": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/reports.Action"
                    }
                },
                "ci": {
                    "$ref": "#/definitions/reports.CIData"
                },
                "conditions": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/result.Condition"
                    }
                },
                "err": {
                    "type": "string"
                },
                "graph": {
                    "type": "string"
                },
                "id": {
                    "description": "ID defines the report ID",
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "pipelineID": {
                    "description": "PipelineID represents the Updatecli manifest pipelineID",
                    "type": "string"
                },
                "reportURL": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "sources": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/result.Source"
                    }
                },
                "targets": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/result.Target"
                    }
                }
            }
        },
        "result.Changelog": {
            "type": "object",
            "properties": {
                "body": {
                    "description": "Body represents the body of the changelog.",
                    "type": "string"
                },
                "publishedAt": {
                    "description": "PublishedAt represents the date the changelog was published.",
                    "type": "string"
                },
                "title": {
                    "description": "Title represents the title of the changelog. Typically a version number.",
                    "type": "string"
                },
                "url": {
                    "description": "URL represents the URL to the changelog.",
                    "type": "string"
                }
            }
        },
        "result.Condition": {
            "type": "object",
            "properties": {
                "config": {
                    "description": "Config stores the source configuration"
                },
                "consoleOutput": {
                    "description": "ConsoleOutput stores the console output of the condition execution",
                    "type": "string"
                },
                "description": {
                    "description": "Description stores the condition execution description.",
                    "type": "string"
                },
                "id": {
                    "description": "ID contains a uniq identifier for the condition",
                    "type": "string"
                },
                "name": {
                    "description": "Name holds the condition name",
                    "type": "string"
                },
                "pass": {
                    "description": "Pass stores the information detected by the condition execution.",
                    "type": "boolean"
                },
                "result": {
                    "description": "Result holds the condition result, accepted values must be one:\n\t\t\t* \"SUCCESS\"\n\t\t\t* \"FAILURE\"\n\t\t\t* \"ATTENTION\"\n\t\t\t* \"SKIPPED\"",
                    "type": "string"
                },
                "scm": {
                    "description": "Scm stores scm information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/result.SCM"
                        }
                    ]
                },
                "sourceID": {
                    "description": "SourceID stores the source ID used by the condition",
                    "type": "string"
                }
            }
        },
        "result.GitBranch": {
            "type": "object",
            "properties": {
                "source": {
                    "description": "Source defines the branch used as a source",
                    "type": "string"
                },
                "target": {
                    "description": "Target defines the branch used by Updatecli to apply the changes done from the working branch",
                    "type": "string"
                },
                "working": {
                    "description": "Working defines the working branch used by Updatecli",
                    "type": "string"
                }
            }
        },
        "result.SCM": {
            "type": "object",
            "properties": {
                "branch": {
                    "description": "Branch defines the different branches used by Updatecli",
                    "allOf": [
                        {
                            "$ref": "#/definitions/result.GitBranch"
                        }
                    ]
                },
                "branchReset": {
                    "description": "BranchReset defines if the scm branch was reset to the base branch during the pipeline execution",
                    "type": "boolean"
                },
                "id": {
                    "description": "ID contains a uniq identifier for the scm",
                    "type": "string"
                },
                "url": {
                    "description": "URL defines the git URL",
                    "type": "string"
                }
            }
        },
        "result.Source": {
            "type": "object",
            "properties": {
                "config": {
                    "description": "Config stores the source configuration"
                },
                "consoleOutput": {
                    "description": "ConsoleOutput stores the console output of the source execution",
                    "type": "string"
                },
                "description": {
                    "description": "Description stores the source execution description",
                    "type": "string"
                },
                "id": {
                    "description": "ID contains a uniq identifier for the source",
                    "type": "string"
                },
                "information": {
                    "description": "Information stores the information detected by the source execution such as a version",
                    "type": "string"
                },
                "name": {
                    "description": "Name holds the source name",
                    "type": "string"
                },
                "result": {
                    "description": "Result holds the source result, accepted values must be one:\n\t\t\t* \"SUCCESS\"\n\t\t\t* \"FAILURE\"\n\t\t\t* \"ATTENTION\"\n\t\t\t* \"SKIPPED\"",
                    "type": "string"
                },
                "scm": {
                    "description": "Scm stores scm information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/result.SCM"
                        }
                    ]
                }
            }
        },
        "result.Target": {
            "type": "object",
            "properties": {
                "changed": {
                    "description": "Changed specifies if the target was modify during the pipeline execution",
                    "type": "boolean"
                },
                "changelogs": {
                    "description": "Changelogs holds the changelog description",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/result.Changelog"
                    }
                },
                "config": {
                    "description": "Config stores the source configuration"
                },
                "consoleOutput": {
                    "description": "ConsoleOutput stores the console output of the target execution",
                    "type": "string"
                },
                "description": {
                    "description": "Description stores the target execution description",
                    "type": "string"
                },
                "dryRun": {
                    "description": "DryRun defines if a target was executed in DryRun mode",
                    "type": "boolean"
                },
                "files": {
                    "description": "Files holds the list of files modified by a target execution",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "ID contains a uniq identifier for the target",
                    "type": "string"
                },
                "information": {
                    "description": "Information stores the old information detected by the target execution",
                    "type": "string"
                },
                "name": {
                    "description": "Name holds the target name",
                    "type": "string"
                },
                "newInformation": {
                    "description": "NewInformation stores the new information updated by during the target execution",
                    "type": "string"
                },
                "result": {
                    "description": "Result holds the target result, accepted values must be one:\n\t\t\t* \"SUCCESS\"\n\t\t\t* \"FAILURE\"\n\t\t\t* \"ATTENTION\"\n\t\t\t* \"SKIPPED\"",
                    "type": "string"
                },
                "scm": {
                    "description": "Scm stores scm information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/result.SCM"
                        }
                    ]
                },
                "sourceID": {
                    "description": "SourceID stores the source ID used by the target",
                    "type": "string"
                }
            }
        },
        "server.AboutResponseModel": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "object",
                    "properties": {
                        "api": {
                            "type": "string"
                        },
                        "buildTime": {
                            "type": "string"
                        },
                        "golang": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "server.ConditionConfigResponse": {
            "type": "object",
            "properties": {
                "configs": {
                    "description": "Configs is a list of configuration conditions.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ConfigCondition"
                    }
                },
                "total_count": {
                    "description": "TotalCount is the total number of conditions for pagination.",
                    "type": "integer"
                }
            }
        },
        "server.ConfigKindResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "server.CreatePipelineReportResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "reportid": {
                    "type": "string"
                }
            }
        },
        "server.DefaultResponseModel": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "server.GetPipelineReportByIDResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.PipelineReport"
                },
                "latestReportByID": {
                    "$ref": "#/definitions/model.PipelineReport"
                },
                "message": {
                    "type": "string"
                },
                "nbReportsByID": {
                    "type": "integer"
                }
            }
        },
        "server.GetPipelineReportsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.SearchLatestReportData"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "server.ListLabelsResponse": {
            "type": "object",
            "properties": {
                "labels": {
                    "description": "Labels is a list of labels.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Label"
                    }
                },
                "total_count": {
                    "description": "TotalCount is the total number of labels matching the query.",
                    "type": "integer"
                }
            }
        },
        "server.ListSCMsResponse": {
            "type": "object",
            "properties": {
                "scms": {
                    "description": "SCMs is a list of SCMs.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SCM"
                    }
                },
                "total_count": {
                    "description": "TotalCount is the total number of SCMs matching the query.",
                    "type": "integer"
                }
            }
        },
        "server.SearchLabelsRequest": {
            "type": "object",
            "properties": {
                "end_time": {
                    "description": "EndTime is the end time for the time range filter\nThis is optional and can be used to filter labels by a specific end time\nTime format is RFC3339: 2006-01-02T15:04:05Z07:00",
                    "type": "string"
                },
                "id": {
                    "description": "Id is the unique identifier of the label.",
                    "type": "string"
                },
                "key": {
                    "description": "Key is the key of the label.",
                    "type": "string"
                },
                "key_only": {
                    "description": "KeyOnly specifies if we only need to retrieve a list of uniq Label keys",
                    "type": "boolean"
                },
                "limit": {
                    "description": "Limit is the maximum number of labels to return\nThis is optional and can be used to limit the number of labels returned",
                    "type": "integer"
                },
                "page": {
                    "description": "Page is the page number for pagination\nThis is optional and can be used to paginate the results",
                    "type": "integer"
                },
                "start_time": {
                    "description": "StartTime is the start time for the time range filter\nThis is optional and can be used to filter labels by a specific start time\nTime format is RFC3339: 2006-01-02T15:04:05Z07:00",
                    "type": "string"
                },
                "value": {
                    "description": "Value is the value of the label.",
                    "type": "string"
                }
            }
        },
        "server.SearchPipelineReportsSummaryRequest": {
            "type": "object",
            "properties": {
                "days": {
                    "description": "Days is the number of days to summarize, today included.\nIt defaults to 7 and is ignored when hours, or start_time and end_time, are provided.",
                    "type": "integer"
                },
                "end_time": {
                    "description": "EndTime is the end time for the time range filter.\nTime format is: 2006-01-02 15:04:05Z07:00",
                    "type": "string"
                },
                "granularity": {
                    "description": "Granularity is the size of the time buckets, one of \"hour\", \"day\", \"week\" or\n\"month\". It defaults to \"day\".",
                    "type": "string"
                },
                "hours": {
                    "description": "Hours is the number of hours to summarize, the current hour included.\nIt cannot be combined with days and is ignored when start_time and end_time are provided.",
                    "type": "integer"
                },
                "labels": {
                    "description": "Labels is a map of labels to filter reports by.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "metric": {
                    "description": "Metric is what the reports are counted by. It defaults to \"result\", which is\nthe only value supported so far.",
                    "type": "string"
                },
                "open_action": {
                    "description": "OpenAction filters reports by whether they carry an action left open, such as a\npull request still waiting to be merged. This is optional: unset does not filter\nanything out, true only counts the reports with an open action and false only the\nones without.\n\nThe same breakdown is reported without filtering anything out under the open_actions\nkey of every bucket.",
                    "type": "boolean"
                },
                "results": {
                    "description": "Results is a list of pipeline results to filter reports by, such as\n\"✔\", \"✗\", \"⚠\" or \"-\". A report is counted when its result is any of them.\nAn empty list does not filter anything out.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scmid": {
                    "description": "ScmID is the ID of the SCM to filter reports by.\nUse \"none\" to only count the reports which are not attached to any SCM.",
                    "type": "string"
                },
                "start_time": {
                    "description": "StartTime is the start time for the time range filter.\nTime format is: 2006-01-02 15:04:05Z07:00",
                    "type": "string"
                }
            }
        },
        "server.SearchPipelineReportsSummaryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data contains one entry per time bucket, ordered from the oldest to the most recent one.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.ReportResultSummaryEntry"
                    }
                },
                "granularity": {
                    "description": "Granularity is the size of the time buckets of the entries.",
                    "type": "string"
                },
                "metric": {
                    "description": "Metric is the metric the reports were counted by.",
                    "type": "string"
                },
                "total_count": {
                    "description": "TotalCount is the total number of reports matching the query.",
                    "type": "integer"
                }
            }
        },
        "server.SearchSCMsRequest": {
            "type": "object",
            "properties": {
                "branch": {
                    "description": "Branch is the SCM branch to filter by.",
                    "type": "string"
                },
                "end_time": {
                    "description": "EndTime is the end time for the time range filter.\nTime format is RFC3339: 2006-01-02T15:04:05Z07:00",
                    "type": "string"
                },
                "labels": {
                    "description": "Labels filters SCM summaries by report labels.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "limit": {
                    "description": "Limit is the maximum number of SCMs to return.",
                    "type": "integer"
                },
                "open_action": {
                    "description": "OpenAction filters SCM summaries by whether a pipeline carries an action left open,\nsuch as a pull request still waiting to be merged. This is optional: unset does not\nfilter anything out, true only keeps the pipelines with an open action and false only\nthe ones without.",
                    "type": "boolean"
                },
                "page": {
                    "description": "Page is the page number for pagination.",
                    "type": "integer"
                },
                "results": {
                    "description": "Results filters SCM summaries by pipeline result, such as \"✔\", \"✗\", \"⚠\" or\n\"-\". An empty list does not filter anything out.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scmid": {
                    "description": "ScmID is the ID of the SCM to filter by.",
                    "type": "string"
                },
                "start_time": {
                    "description": "StartTime is the start time for the time range filter.\nTime format is RFC3339: 2006-01-02T15:04:05Z07:00",
                    "type": "string"
                },
                "summary": {
                    "description": "Summary indicates if the response should contain SCM summary data.",
                    "type": "boolean"
                },
                "url": {
                    "description": "URL is the SCM URL to filter by.",
                    "type": "string"
                }
            }
        },
        "server.SourceConfigResponse": {
            "type": "object",
            "properties": {
                "configs": {
                    "description": "Configs is a list of configuration sources.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ConfigSource"
                    }
                },
                "total_count": {
                    "description": "TotalCount is the total number of sources for pagination.",
                    "type": "integer"
                }
            }
        },
        "server.TargetConfigResponse": {
            "type": "object",
            "properties": {
                "configs": {
                    "description": "Configs is a list of configuration targets.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ConfigTarget"
                    }
                },
                "total_count": {
                    "description": "TotalCount is the total number of targets for pagination.",
                    "type": "integer"
                }
            }
        },
        "source.Config": {
            "type": "object",
            "properties": {
                "dependsOn": {
                    "description": "\"dependson\" allows to specify the order of execution of resources.\nIt accepts a list of rules like \"(resourceType#)resourceId(:booleanOperator)\".\n\nThe resourceType is optional and can be one of \"condition\", \"source\" or \"target\"\nBy default the resourceType is the current resource type\n\nThe resourceId is the name of the resource to depend on\n\nThe booleanOperator is optional and can be \"AND\" or \"OR\"\n\nexamples:\n   dependson:\n     * condition#myCondition:and\n     * source#mySource\n\nremarks:\n * The parameters \"sourceid\" and \"conditionsids\" affect the order of resource execution.\n * To avoid circular dependencies, the depended resource may need to remove any conditionids or set \"disablesourceinput to true\".",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "deprecatedDependsOn": {
                    "description": "!deprecated, please use dependson\nDeprecatedDependsOn is kept for backward compatibility",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "deprecatedSCMID": {
                    "description": "!deprecated, please use scmid\nDeprecatedSCMID is kept for backward compatibility",
                    "type": "string"
                },
                "kind": {
                    "description": "kind specifies the resource kind which defines accepted spec value",
                    "type": "string"
                },
                "name": {
                    "description": "name specifies the resource name",
                    "type": "string"
                },
                "scmid": {
                    "description": "scmid specifies the scm configuration key associated to the current resource",
                    "type": "string"
                },
                "spec": {
                    "description": "spec specifies parameters for a specific resource kind"
                },
                "transformers": {
                    "description": "transformers defines how the default input value need to be transformed",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/transformer.Transformer"
                    }
                }
            }
        },
        "target.Config": {
            "type": "object",
            "properties": {
                "dependsOn": {
                    "description": "\"dependson\" allows to specify the order of execution of resources.\nIt accepts a list of rules like \"(resourceType#)resourceId(:booleanOperator)\".\n\nThe resourceType is optional and can be one of \"condition\", \"source\" or \"target\"\nBy default the resourceType is the current resource type\n\nThe resourceId is the name of the resource to depend on\n\nThe booleanOperator is optional and can be \"AND\" or \"OR\"\n\nexamples:\n   dependson:\n     * condition#myCondition:and\n     * source#mySource\n\nremarks:\n * The parameters \"sourceid\" and \"conditionsids\" affect the order of resource execution.\n * To avoid circular dependencies, the depended resource may need to remove any conditionids or set \"disablesourceinput to true\".",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dependsOnChange": {
                    "description": "dependsonchange enables the mechanism to check if the dependant target(s) have made a change.\nIf the dependant target(s) have not made a change the target will be skipped.\n\ndefault:\n  false",
                    "type": "boolean"
                },
                "deprecatedConditionIDs": {
                    "description": "! Deprecated - please use DependsOn with ` + "`" + `condition#conditionid` + "`" + ` keys\n\nconditionids specifies the list of conditions to be evaluated before running the target.\nif at least one condition is not met, the target will be skipped.\n\ndefault:\n  by default, all conditions are evaluated.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "deprecatedDependsOn": {
                    "description": "!deprecated, please use dependson\nDeprecatedDependsOn is kept for backward compatibility",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "deprecatedSCMID": {
                    "description": "!deprecated, please use scmid\nDeprecatedSCMID is kept for backward compatibility",
                    "type": "string"
                },
                "deprecatedSourceID": {
                    "description": "! Deprecated - please use all lowercase ` + "`" + `sourceid` + "`" + `",
                    "type": "string"
                },
                "disableConditions": {
                    "description": "disableconditions disables the mechanism to evaluate all conditions before running the target.\n\ndefault:\n  false\n\nremark:\n It's possible to only monitor specific conditions by setting disableconditions to true\n and using DependsOn with ` + "`" + `condition#conditionid` + "`" + ` keys",
                    "type": "boolean"
                },
                "disableSourceInput": {
                    "description": "disablesourceinput disables the mechanism to retrieve a default value from a source.\nFor example, if true, source information like changelog will not be accessible for a github/pullrequest action.\n\ndefault:\n false",
                    "type": "boolean"
                },
                "kind": {
                    "description": "kind specifies the resource kind which defines accepted spec value",
                    "type": "string"
                },
                "name": {
                    "description": "name specifies the resource name",
                    "type": "string"
                },
                "scmid": {
                    "description": "scmid specifies the scm configuration key associated to the current resource",
                    "type": "string"
                },
                "sourceID": {
                    "description": "sourceid specifies where retrieving the default value.\n\ndefault:\n  if only one source is defined, then sourceid is set to that sourceid.",
                    "type": "string"
                },
                "spec": {
                    "description": "spec specifies parameters for a specific resource kind"
                },
                "transformers": {
                    "description": "transformers defines how the default input value need to be transformed",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/transformer.Transformer"
                    }
                }
            }
        },
        "transformer.FindSubMatch": {
            "type": "object",
            "properties": {
                "captureIndex": {
                    "description": "CaptureIndex defines which substring occurrence to retrieve. Note also that a value of ` + "`" + `0` + "`" + ` for ` + "`" + `captureIndex` + "`" + ` returns all submatches, and individual submatch indexes start at ` + "`" + `1` + "`" + `.",
                    "type": "integer"
                },
                "capturePattern": {
                    "description": "Uses the match group(s) to generate the output using \\0, \\1, \\2, etc",
                    "type": "string"
                },
                "deprecatedCaptureIndex": {
                    "type": "integer"
                },
                "pattern": {
                    "description": "Pattern defines regular expression to use for retrieving a submatch",
                    "type": "string"
                }
            }
        },
        "transformer.JsonMatch": {
            "type": "object",
            "properties": {
                "joinMultipleMatches": {
                    "description": "If we find multiple matches, join them by this",
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "multipleMatchSelector": {
                    "description": "If we find multiple matches, select the \"first\" or the \"last\"",
                    "type": "string"
                },
                "noMatchResult": {
                    "description": "If we don't find a match then return the following string or the input value",
                    "type": "string"
                }
            }
        },
        "transformer.Replacer": {
            "type": "object",
            "properties": {
                "from": {
                    "description": "From defines the source value which need to be replaced",
                    "type": "string"
                },
                "to": {
                    "description": "To defines the \"to what\" a \"from\" value needs to be replaced",
                    "type": "string"
                }
            }
        },
        "transformer.Transformer": {
            "type": "object",
            "properties": {
                "addPrefix": {
                    "description": "AddPrefix adds a prefix to the transformer input value",
                    "type": "string"
                },
                "addSuffix": {
                    "description": "AddSuffix adds a suffix to the transformer input value",
                    "type": "string"
                },
                "deprecatedAddPrefix": {
                    "type": "string"
                },
                "deprecatedAddSuffix": {
                    "type": "string"
                },
                "deprecatedFindSubMatch": {},
                "deprecatedSemVerInc": {
                    "type": "string"
                },
                "deprecatedTrimPrefix": {
                    "type": "string"
                },
                "deprecatedTrimSuffix": {
                    "type": "string"
                },
                "find": {
                    "description": "Find searches for a specific value if it exists and return false if it doesn't",
                    "type": "string"
                },
                "findSubMatch": {
                    "description": "Find searches for a specific value if it exists then return the value using regular expression",
                    "allOf": [
                        {
                            "$ref": "#/definitions/transformer.FindSubMatch"
                        }
                    ]
                },
                "jsonMatch": {
                    "$ref": "#/definitions/transformer.JsonMatch"
                },
                "quote": {
                    "description": "Quote add quote around the value",
                    "type": "boolean"
                },
                "replacer": {
                    "description": "Replacer specifies what value needs to be changed and how",
                    "allOf": [
                        {
                            "$ref": "#/definitions/transformer.Replacer"
                        }
                    ]
                },
                "replacers": {
                    "description": "Replacers specifies a list of replacer instruction",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/transformer.Replacer"
                    }
                },
                "semVerInc": {
                    "description": "SemvVerInc specifies a comma separated list semantic versioning component that needs to be upgraded.",
                    "type": "string"
                },
                "trimPrefix": {
                    "description": "TrimPrefix removes a prefix to the transformer input value",
                    "type": "string"
                },
                "trimSuffix": {
                    "description": "TrimSuffix removes the suffix from the transformer input value",
                    "type": "string"
                },
                "unquote": {
                    "description": "Unquote remove quotes around the value",
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
