BEGIN;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS scms (
   id uuid DEFAULT uuid_generate_v4(),
   branch VARCHAR NOT NULL,
   url VARCHAR NOT NULL,
   created_at TIMESTAMPTZ DEFAULT NOW(),
   updated_at TIMESTAMPTZ DEFAULT NOW()
);
COMMIT;
