apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "udash.fullname" . }}-server
  labels:
    {{- include "udash.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "udash.selectorLabels.server" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "udash.selectorLabels.server" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "udash.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.server.repository }}:{{ .Values.images.server.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.server.pullPolicy }}
          env:
            - name: UDASH_DB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "udash.secretName" . }}-database
                  key: uri
            - name: UDASH_AUTH_MODE
              valueFrom:
                secretKeyRef:
                  name: {{ include "udash.secretName" . }}-auth
                  key: mode
            - name: UDASH_AUTH_ISSUER
              valueFrom:
                secretKeyRef:
                  name: {{ include "udash.secretName" . }}-auth
                  key: issuer
            - name: UDASH_AUTH_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: {{ include "udash.secretName" . }}-auth
                  key: audience
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/ping
              port: http
          readinessProbe:
            httpGet:
              path: /api/ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: "config-volume"
              mountPath: "/etc/udash/"
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "udash.configMapName" . }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
