apiVersion: v1
kind: Secret
metadata:
  name: {{ include "udash.secretName" . }}-auth
  labels:
    {{- include "udash.labels" . | nindent 4 }}
  {{- with .Values.secrets.auth.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  mode: {{ .Values.secrets.auth.stringdata.mode }}
  clientid: {{ .Values.secrets.auth.stringdata.clientid }}
  audience: {{ .Values.secrets.auth.stringdata.audience }}
  issuer: {{ .Values.secrets.auth.stringdata.issuer }}

