apiVersion: v1
kind: Secret
metadata:
  name: {{ include "udash.secretName" . }}-database
  labels:
    {{- include "udash.labels" . | nindent 4 }}
  {{- with .Values.secrets.database.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  uri: {{ .Values.secrets.database.stringdata.uri }}

