name: Test Typos
on: [pull_request]
permissions: {}
jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Check spelling of file.txt
        uses: crate-ci/typos@15fa374392e479e54ad541a4fd452a1063f3695a # renovate/phf_codegen-0.x
